# file: mysql/tasks/configure.yml

- name: MySQL | Get MySQL version.
  shell: dpkg -s mysql-server | grep ^Version | awk '{ print $2 }'
  register: mysql_cli_version

- name: MySQL | Update the my.cnf
  template:
    src: etc_mysql_my.cnf.j2
    dest: /etc/mysql/my.cnf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart mysql
