# file: mysql/tasks/main.yml

- import_tasks: install.yml
- import_tasks: configure.yml
- import_tasks: secure.yml
- import_tasks: databases.yml
- import_tasks: users.yml
- import_tasks: monit.yml
  when: monit_protection is defined and monit_protection == true
